[package]
name = "compiler"
version = "0.1.0"
authors = ["rowlandsonpratt <striderman34@gmail.com>"]

[dependencies]
llvm-alt = { git="https://github.com/Lapz/llvm-rs.git" }
llvm-sys = "40.0.0"
libc = "0.2"
syntax = {path= "../syntax"}
util = {path= "../util"}